<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromArray;
use App\PKWKaryawan;

class PKWKaryawanExportMaster implements FromArray
{
    protected $ids;

    public function __construct($ids)
    {
        $this->ids = $ids;
    }

    public function array() : array
    {
        $data = [];
        $data[] = [
            "No. Urut",
            "NIK",
            "TANGGAL",
            "NO",
            "NAMA",
            "JABATAN",
            "DEPARTEMEN",
            "SECTION",
            "WORK GROUP",
            "SUB WORK GROUP",
            "Area",
            "Group",
            "No",
            "No KK",
            "NIK/KITAS/KITAP",
            "Nama Lengkap",
            "HUBKEL 1 = P
            2 = S
            3 = I
            4 = A
            5 = T",
            "Tempat Lahir",
            "Tanggal Lahir",
            "Jenis Ke1amin 1=1  2=2",
            "Status Kawin             1=BK, 2=K,     3=CH, 4=CM
            5 = TDK TAU",
            "Alamat Tempat Tinggal",
            "RT",
            "RW",
            "Kode Pos",
            "Kode Kecamatan (diisi petugas)",
            "Nama Kecamatan",
            "Kode Desa (diisi petugas)",
            "Nama Desa",
            "Kode Faskes Tk.I (diisi petugas)",
            "Nama Faskes Tk.I",
            "Kode Faskes Dokter Gigi",
            "Nama Faskes Dokter Gigi",
            "Nomor Telepon Peserta",
            "Email",
            "NPP",
            "Jabatan",
            "Status       1=Tetap, 2=Kontrak, 3=Paruh waktu 4=Penerima Pensiun",
            "Kelas Rawat 1=Kelas I, 2=Kelas II, 3=Kelas III",
            "TMT Kerja (Kary. Aktif)",
            "Gaji Pokok + Tunj. Tetap (Kary. Aktif)",
            "Kewarga Negaraan 1=WNI, 2=WNA",
            "No. Polis",
            "Nama Asuransi",
            "No. NPWP",
            "No Passport",
            "Status L/K",
            "AGAMA",
            "ALAMAT KTP",
            "MASA BERLAKU KTP",
            "Golongan Darah",
            "No NPWP",
            "STATUS PAJAK",
            "STATUS PERDATA",
            "Date",
            "HP - 1",
            "HP - 2",
            "Jenjang",
            "Jurusan",
            "AYAH",
            "IBU",
            "Mertua", // Bapak
            "Mertua", // Ibu
            "Kandung (1)",
            "kandung (2)",
            "Kandung (3)",
            "Via",
            "Status Karyawan",
            "Pengangkatan",
            "Kode Wings",
            "Kontrak Mulai",
            "Kontrak Berakhir",
            "Kode",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "NIK",
            "NAMA SEKOLAH"
        ];

        $data[] = [
            '', // "No. Urut",
            '', // "NIK",
            '', // "TANGGAL",
            '', // "NO",
            '', // "NAMA",
            '', // "JABATAN",
            '', // "DEPARTEMEN",
            '', // "SECTION",
            '', // "WORK GROUP",
            '', // "SUB WORK GROUP",
            '', // "Area",
            '', // "Group",
            '1', // "No",
            '2', // "No KK",
            '3', // "NIK/KITAS/KITAP",
            '4', // "Nama Lengkap",
            '5', // "HUBKEL 1 = P 2 = S 3 = I 4 = A 5 = T",
            '6', // "Tempat Lahir",
            '7', // "Tanggal Lahir",
            '8', // "Jenis Ke1amin 1=1  2=2",
            '9', // "Status Kawin             1=BK, 2=K,     3=CH, 4=CM 5 = TDK TAU",
            '10', // "Alamat Tempat Tinggal",
            '11', // "RT",
            '12', // "RW",
            '13', // "Kode Pos",
            '14', // "Kode Kecamatan (diisi petugas)",
            '15', // "Nama Kecamatan",
            '16', // "Kode Desa (diisi petugas)",
            '17', // "Nama Desa",
            '18', // "Kode Faskes Tk.I (diisi petugas)",
            '19', // "Nama Faskes Tk.I",
            '20', // "Kode Faskes Dokter Gigi",
            '21', // "Nama Faskes Dokter Gigi",
            '22', // "Nomor Telepon Peserta",
            '23', // "Email",
            '24', // "NPP",
            '25', // "Jabatan",
            '26', // "Status       1=Tetap, 2=Kontrak, 3=Paruh waktu 4=Penerima Pensiun",
            '27', // "Kelas Rawat 1=Kelas I, 2=Kelas II, 3=Kelas III",
            '28', // "TMT Kerja (Kary. Aktif)",
            '29', // "Gaji Pokok + Tunj. Tetap (Kary. Aktif)",
            '30', // "Kewarga Negaraan 1=WNI, 2=WNA",
            '31', // "No. Polis",
            '32', // "Nama Asuransi",
            '33', // "No. NPWP",
            '34', // "No Passport",
            '', // "Status L/K",
            '', // "AGAMA",
            '', // "ALAMAT KTP",
            '', // "MASA BERLAKU KTP",
            '', // "Golongan Darah",
            '', // "No NPWP",
            '', // "STATUS PAJAK",
            '', // "STATUS PERDATA",
            '', // "Date",
            '', // "HP - 1",
            '', // "HP - 2",
            '', // "Jenjang",
            '', // "Jurusan",
            '', // "AYAH",
            '', // "IBU",
            '', // "Mertua", // Bapak
            '', // "Mertua", // Ibu
            '', // "Kandung (1)",
            '', // "kandung (2)",
            '', // "Kandung (3)",
            '', // "Via",
            '', // "Status Karyawan",
            '', // "Pengangkatan",
            '', // "Kode Wings",
            'Mulai', // "Kontrak Mulai",
            'Berakhir', // "Kontrak Berakhir",
            'Kontrak', // "Kode",
            'JAMSOSTEK', // "",
            'PAJAK', // "",
            '', // "",
            'STATUS', // "",
            'JML.ANAK', // "",
            'KLINIK', // "",
            'KODE', // "",
            'TK', // "NIK",
            '', // "NAMA SEKOLAH"
        ];

        $employees = PKWKaryawan::whereIn('id', explode(',', $this->ids))->orderByRaw('SUBSTR(nik, 8) asc')->get();
        foreach($employees as $employee) {
            $data[] = [
                '', //"No. Urut"
                $employee->nik, //"NIK"
                $employee->tanggal_masuk,
                '', //"NO"
                $employee->nama, // NAMA
                $employee->jabatan->nama_jabatan, // "JABATAN"
                $employee->divisi->kode_divisi,
                $employee->bagian->kode_bagian, //"SECTION",
                '', // "WORK GROUP",
                '', //"SUB WORK GROUP",
                '', //"Area",
                '', //"Group",
                '', //"No",
                $employee->no_kk." ", //"No KK",
                $employee->nik_ktp." ", //"NIK/KITAS/KITAP",
                $employee->nama, //"Nama Lengkap",
                '1', //"HUBKEL 1 = P2 = S 3 = I 4 = A 5 = T",
                $employee->tempat_lahir, // "Tempat Lahir",
                $employee->tanggal_lahir, //"Tanggal Lahir",
                $employee->jenis_kelamin, //"Jenis Ke1amin 1=1  2=2",
                'L', //"Status Kawin 1=BK, 2=K,     3=CH, 4=CM 5 = TDK TAU",
                $employee->alamat_ktp.', Kel. '.ucfirst(strtolower($employee->ktp_desa->name)).', Kec. '.ucfirst(strtolower($employee->ktp_kecamatan->name)).', Kota. '.ucfirst(strtolower($employee->ktp_kota->name)).', Provinsi '.ucfirst(strtolower($employee->ktp_provinsi->name)), //"Alamat Tempat Tinggal",
                '', //"RT",
                '', //"RW",
                '', //"Kode Pos",
                '', //"Kode Kecamatan (diisi petugas)",
                ucfirst(strtolower($employee->ktp_kecamatan->name)), //"Nama Kecamatan",
                '', //"Kode Desa (diisi petugas)",
                ucfirst(strtolower($employee->ktp_desa->name)), //"Nama Desa",
                '', //"Kode Faskes Tk.I (diisi petugas)",
                '', //"Nama Faskes Tk.I",
                '', //"Kode Faskes Dokter Gigi",
                '', //"Nama Faskes Dokter Gigi",
                $employee->nomor_hp, //"Nomor Telepon Peserta",
                $employee->email, //"Email",
                '', //"NPP",
                $employee->jabatan->nama_jabatan, //"Jabatan",
                '', //"Status       1=Tetap, 2=Kontrak, 3=Paruh waktu 4=Penerima Pensiun",
                '', //"Kelas Rawat 1=Kelas I, 2=Kelas II, 3=Kelas III",
                '', //"TMT Kerja (Kary. Aktif)",
                '', //"Gaji Pokok + Tunj. Tetap (Kary. Aktif)",
                'WNI', //"Kewarga Negaraan 1=WNI, 2=WNA",
                '', //"No. Polis",
                '', //"Nama Asuransi",
                $employee->no_npwp, //"No. NPWP",
                '', //"No Passport",
                '', //"Status L/K",
                $employee->agama, //"AGAMA",
                $employee->alamat_ktp.', Kel. '.ucfirst(strtolower($employee->ktp_desa->name)).', Kec. '.ucfirst(strtolower($employee->ktp_kecamatan->name)).', Kota. '.ucfirst(strtolower($employee->ktp_kota->name)).', Provinsi '.ucfirst(strtolower($employee->ktp_provinsi->name)), //"Alamat Tempat Tinggal",
                'Seumur hidup', //"MASA BERLAKU KTP",
                '', //"Golongan Darah",
                $employee->no_npwp, //"No NPWP",
                '', //"STATUS PAJAK",
                '', //"STATUS PERDATA",
                '', //"Date",
                '', //"HP - 1",
                '', //"HP - 2",
                $employee->pendidikan, //"Jenjang",
                $employee->jurusan, //"Jurusan",
                $employee->nama_ayah, //"AYAH",
                $employee->nama_ibu, //"IBU",
                $employee->nama_ayah_mertua, //"Mertua", // Bapak
                $employee->nama_ibu_mertua, //"Mertua", // Ibu
                '', //"Kandung (1)",
                '', //"kandung (2)",
                '', //"Kandung (3)",
                '', //"Via",
                '', //"Status Karyawan",
                '', //"Pengangkatan",
                '', //"Kode Wings",
                '', //"Kontrak Mulai",
                '', //"Kontrak Berakhir",
                '', //"Kode",
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '', //"NIK",
                $employee->nama_sekolah//"NAMA SEKOLAH"
            ];
        }

        return $data;
    }
}
